name: CI/CD Pipeline

on: 
    push: 
        branches: 
            - main
    pull_request:
        branches:
            - main

jobs:
  frontend:
    name: Frontend
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['20.x']

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: |
          cd frontend
          npm ci
          npm run build --if-present
          cd ..
          sudo cp -r frontend/dist/frontend/browser backend/cmd/strichliste/frontendDist


  backend:
    name: Backend
    needs: frontend
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.21.x' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Test Go
        run: |
          cd backend
          go test ./...