name: CI/CD Pipeline

on: 
    push: 
        branches: 
            - main
    pull_request:
        branches:
            - main

jobs:
    unit-test:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Install Dependencies
            run: |
              sudo apt update
              sudo apt install golang-go -y
              sudo apt install nodejs -y
              cd frontend
              npm ci

          
          - name: Frontend
            run: |
              cd frontend
              ng build --prod --output-path=frontendDist
              ng test

          - name: Backend
            run: |
              cd backend
              go test ./...
          